name: Git Semantic Version
run-name: ${{ github.actor }} is testing out GitHub Actions with semantic version 🚀
on: 
  pull_request:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # important parameter
      - name: Git Semantic Version
        id: versioning
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "v${major}.${minor}.${patch}-prerelease${increment}"  
          search_commit_body: true
          bump_each_commit: true
